name: CustomEnchantment
main: com.bafmc.customenchantment.CustomEnchantment
version: 1.0.0
api-version: 1.21
author: TexWard
depend: [BafFramework]
softdepend: [CustomMenu, StackMob, Vouchers, ItemDropManager, mcMMO, PlaceholderAPI, PlaceholderAPIAddon, CustomShop, DamageIndicator, CustomFarm]
description: Support for custom enchantment
libraries:
  - 'org.apache.poi:poi-ooxml:5.2.5'
commands:
  customenchantment:
    description: CustomEnchantment main commands
    usage: /<command>
    aliases: [ce, cem, cenchant]
  tinkerer:
    description: Tinkerer CustomEnchantment item
    usage: /<command>
  tinkerer-new:
    description: Tinkerer CustomEnchantment item (new API)
    usage: /<command>
  bookcraft:
    description: Craft CustomEnchantment book
    usage: /<command>
    aliases: [bookc, cecraft]
  bookcraft-new:
    description: Craft CustomEnchantment book (new API)
    usage: /<command>
  bookupgrade:
    description: Craft CustomEnchantment book
    usage: /<command>
    aliases: [bookup, ceup]
  ceanvil:
    description: Anvil CustomEnchantment item
    usage: /<command>
  ceanvil-new:
    description: Anvil CustomEnchantment item (new API)
    usage: /<command>
  nametag:
    description: Nametag for CustomEnchantment item
    usage: /<command>
  equipment:
    description: Equipment for CustomEnchantment item
    usage: /<command>
    aliases: [e, equip]
  artifactupgrade:
    description: Equipment for CustomEnchantment item
    usage: /<command>
    aliases: [au, aup]
  cefilter:
    description: Filter for CustomEnchantment item
    usage: /<command>
  autoattack:
    description: Auto attack CustomEnchantment item
    usage: /<command>