package com.bafmc.customenchantment.item;

public enum CEWeaponType {
    HELMET, CHESTPLATE, LEGGINGS, BOOTS,
    SWORD, DAGGER, SPEAR, GREATSWORD, AXE, HAMMER, STICK, STAFF, SCYTHE, TRIDENT,
    BOW, CROSSBOW,
    PICKAXE, SHOVEL, HOE, FISHINGROD,
    SHIELD,
    WINGS, HAT
}
